spring.application.name=makemytrip
server.port=8000
spring.mongodb.uri=mongodb+srv://admin:admin@main.ijwkl02.mongodb.net/makemytrip?retryWrites=true&w=majority
spring.mongodb.database=makemytrip
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration